[bumpver]
current_version = "0.1.48"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"setup.py" = [
    "version=\"{version}\",",
]
"src/moralis/evm_api/version.py" = [
    "^__version__ = \"{version}\"$",
]

"src/moralis/sol_api/version.py" = [
    "^__version__ = \"{version}\"$",
]

"src/moralis/auth/version.py" = [
    "^__version__ = \"{version}\"$",
]

"src/moralis/streams/version.py" = [
    "^__version__ = \"{version}\"$",
]

